# Copyright 2021 James Page
# See LICENSE file for licensing details.

options:
  weather-api-token:
    default:
    description: API token for weather integration
    type: string
  external-hostname:
    default: open-apiary.juju
    description: External hostname to access the Open Apiary Web application
    type: string
